services:
  postgres:
    image: postgres:16
    container_name: crm_auto_lote_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: crm
      POSTGRES_PASSWORD: crm
      POSTGRES_DB: crm_auto_lote
    ports:
      - "5432:5432"
    volumes:
      - crm_auto_lote_pg:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: crm_auto_lote_redis
    restart: unless-stopped
    ports:
      - "6379:6379"

volumes:
  crm_auto_lote_pg:
